### ISSUE TITLE
Add Apache James

### ISSUE THREAD

**Issue by kenballus** [kenballus/smtp-garden#1]
https://james.apache.org/

**Comment by schongallam** [comment]
I have built james 3.7.5 from source, it takes about 10gb.  I have not been able to get james 3.8.1 to build from github source however -- numerous missing symbols.  The official docker container is 500mb (for version 3.6.1, however).

**Comment by schongallam** [comment]
I got version of 3.8.1 to `mvn compile` but not `mvn install`.  After switching over to the official Apache pre-compiled binaries for 3.8.1, I'm able to get the server running now (on OpenJDK 17, no less).  There are still some more things I can try to get the build-from-source to work (like forcing downgrade to OpenJDK 11).  But even on appleseed the build takes at least ~15 minutes and is a disk hog.  So if the latest binaries are satisfactory, I'll move on to finishing the server configuration.

**Comment by kenballus** [comment]
Thank you. I will take a look at this and get back to you by the weekend.

-Ben

**Comment by schongallam** [comment]
Builds from source zip (3.8.1).  Next step is to migrate to github accession.

**Comment by schongallam** [comment]
With commit fc5d3da James now pulls directly from james-project:master.  Image efficiency improved, down from 8~12gb to 2.5gb.  Still uses the .../conf/ folder to bulk deliver configuration files, because reasons (and which should be fine for the time being).  Should that need a fresh look, it can be opened as its own issue, as needed.  I'll close this issue for now.

The most noteworthy change was James now depends on Java 21... a big step up from 11.

Being that 3.8.1 is the official latest stable release, I left a fallback Dockerfile for building that image too.
